apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sunservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sunservice
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50