apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: website
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: website
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50