apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: windservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: windservice
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50